# Generated by Django 5.0.6 on 2024-05-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
